### ISSUE TITLE
Set minimum deployment target

### ISSUE THREAD

**Issue by dimitris-c** [chronotruck/FlagPhoneNumber#101]
**Describe the bug**
Carthage builds not usable for projects targeting <12.2

**To Reproduce**
1. Use Carthage on a project with lower deployment target than 12.2
2. Build project
3. :boom:

**Expected behavior**
Projects should build.

**Screenshots**
n/a

 **FlagPhoneNumber (please complete the following information):**
 - Latest version

PR created #100

**Comment by grifas** [comment]
Merged. https://github.com/chronotruck/FlagPhoneNumber/pull/100

**Comment by iamszabo** [comment]
There was no release containing this change. Could we have a release for this?
