### ISSUE TITLE
Can't compile in Xcode 10.3

### ISSUE THREAD

**Issue by Ku6ep** [chronotruck/FlagPhoneNumber#107]
The project can't compile with a pod of FPN in Xcode 10.3

Error from Xcode: 
/Users/.../.../Pods/FlagPhoneNumber/Sources/Resources/FPNCountryView.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fe6381a64f0> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7fe6381a68f0> scaleFactor=2x'. These intermediate objects were non-nil: (

**Comment by gd08xxx** [comment]
I had the same issue as well. How did you fix it?

**Comment by Ku6ep** [comment]
> I am having the same issue as well. How did you fix it?

Just restart mac or try this in terminal:
`sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService`
