### ISSUE TITLE
iOS 13 wrong layout, text and flags overlapped

### ISSUE THREAD

**Issue by klebeer** [chronotruck/FlagPhoneNumber#112]
**Describe the bug**

Using  FlagPhoneNumber on iOS 13 beta 5,   causes a incorrect rendering of  flags and phone numbers.

My dev environment:

- MacOS Catalina Beta
- Xcode 11 beta 4
- iPhone XS with iOS 13 beta 5

**To Reproduce**
Using  Xcode 11 Beta and IOs 13 beta  install ExampleCocoapods

**Screenshots**
![IMG_F4827233D3CC-1](https://user-images.githubusercontent.com/1549668/62133635-b904f000-b2a4-11e9-9ed0-9296c55d52e4.jpeg)
![IMG_0709 2](https://user-images.githubusercontent.com/1549668/62133640-bbffe080-b2a4-11e9-8c1d-8428317c4613.PNG)

**Comment by talk812** [comment]
same question please help~~~~

**Comment by grifas** [comment]
Can you try with the ‘fix_layout’ branch ?

**Comment by talk812** [comment]
i'm using cocoapods , How should i do to change the branch, please help

**Comment by talk812** [comment]
i've change to that branch and  it fixed. When will this be merge to master? or is there another issue exist on other version?

**Comment by grifas** [comment]
I will try to push a new release with this fix today.

**Comment by grifas** [comment]
I pushed the fix on a new release (`0.7.7`).
