### ISSUE TITLE
When flag images aren't showing the alternative unknown flag doesn't appear

### ISSUE THREAD

**Issue by lsamaria** [chronotruck/FlagPhoneNumber#123]
For some reason when I have a programmatic collectionView and I present the vc with the `FPNTextField` class the flag doesn't appear. 

![Screen Shot 2019-09-18 at 6 15 04 PM](https://user-images.githubusercontent.com/15787990/65365272-2cace480-dbe6-11e9-88bd-7b6154d2c1e4.png)

Another problem as you can see in the photo above, the `unknown` image in your asset catalog doesn't appear in either the `FPNTextField` at the top nor the `FPNCountryPicker` at the bottom. When I look into the asset folder these are the errors I see:

![Screen Shot 2019-09-18 at 6 16 28 PM](https://user-images.githubusercontent.com/15787990/65366236-4e5e9980-dbef-11e9-9c8f-bfb7fbd4d284.png)

![Screen Shot 2019-09-18 at 6 16 51 PM](https://user-images.githubusercontent.com/15787990/65366240-57e80180-dbef-11e9-8150-3e066c0d9a6d.png)

In the FPNCountry file when the images get loaded, if an image can't be found the `unknown` image is provided as a fallback image but there isn't an alternative for the `unknown` image

![Screen Shot 2019-09-15 at 11 38 56 PM](https://user-images.githubusercontent.com/15787990/65365406-1c493980-dbe7-11e9-970d-2260eadfda99.png)

[I tried this fix (red arrow in below pic)](https://stackoverflow.com/a/38726665/4833705) for the asset catalog warning but nada.

![Screen Shot 2019-09-20 at 9 42 25 PM](https://user-images.githubusercontent.com/15787990/65366310-20c62000-dbf0-11e9-93ad-fe3965d0f6b9.png)

As for as the initial problem itself I don't have the problem with any other classes that present the vc with the FPNTextField because all the flags appear. All my code is programmatic so it's easy to just c+p and move the presenter code around. The problem only happens in classes with a collectionView. I narrowed it down to the constraints, for whatever reason the cv constraints in one class somehow affects the flags in another class. These are the constraints I use:

    collectionView.translates.... = false
    view.addSubview(collectionView)
        
    collectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
    collectionView.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor, constant: 0).isActive = true
    collectionView.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor, constant: 0).isActive = true
    collectionView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor).isActive = true.

I also tried setting the cv size to `view.bounds` when I instantiate it but the same problem occurred:

    lazy var collectionView: UICollectionView = {

        let layout = UICollectionViewFlowLayout()
        layout.sectionInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        
        let collectionView = UICollectionView(frame: view.bounds, collectionViewLayout: layout)
        collectionView.delegate = self
        collectionView.dataSource = self
        collectionView.alwaysBounceVertical = true
        // ...
        collectionView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        collectionView.scrollIndicatorInsets = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        return collectionView
    }()

This problem occurs wether pushing on presenting.

**To Reproduce**

Create a programmatic collectionView with the same constraints I used above. Add a barButtonItem and for it's target action either push or present another vc that contains the FPNTextField

**Expected behavior**
The flags should appear and when they don't **the `unknown` image should appear**

**Screenshots**
see above

**Smartphone (please complete the following information):**
iPhone 7+ and all the simulator iPhones and iPads

 **FlagPhoneNumber (please complete the following information):**
- FlagPhoneNumber (0.7.6):
- FlagPhoneNumber/libPhoneNumberiOS (= 0.7.6)
- FlagPhoneNumber/libPhoneNumberiOS (0.7.6)
-Xcode 10.2.1
-Swift 5

**Additional context**

**Comment by lsamaria** [comment]
I’ll try it later tonight and get back to you.

Btw I got it to work with the Apple emoji. I just had to clean the derived data after changing the code.

**Comment by lsamaria** [comment]
I haven’t had a chance to get to it yet. I’m working on 3 apps and hoping to release them this week. Once I get them to the AppStore I’ll immediately jump on top of this.

**Comment by lsamaria** [comment]
I finally got a chance to download the new Podfile. You fixed the issue, thanks!!!

**Comment by venkateshwarlut** [comment]
@lsamaria can you please tell me which pod version fixed ??? currently I'm suing 0.8.0 not working for me.

**Comment by lsamaria** [comment]
@venkateshwarlut This pod is no longer supported. The last commit was Dec 2019. I switched to [phoneNumberKit](https://github.com/marmelroy/PhoneNumberKit). It's very easy to use. Let me know if you need some help setting up, I'll send some code.

**Comment by venkateshwarlut** [comment]
@

> @venkateshwarlut This pod is no longer supported. The last commit was Dec 2019. I switched to [phoneNumberKit](https://github.com/marmelroy/PhoneNumberKit). It's very easy to use. Let me know if you need some help setting up, I'll send some code.

Yes please share me sample code. I will check and setup.

**Comment by lsamaria** [comment]
@venkateshwarlut

In `checkPhoneNumberValidity()` you want to check `if isNumberValid ...` then do whatever with all of the info


```
import PhoneNumberKit

lazy var phoneNumberTextField: PhoneNumberTextField = {
        let textField = PhoneNumberTextField()
        textField.translatesAutoresizingMaskIntoConstraints = false
        textField.font = UIFont.systemFont(ofSize: 19)
        textField.textColor = UIColor.black
        textField.autocorrectionType = .no
        textField.keyboardType = .phonePad
        textField.layer.borderWidth = 1
        textField.layer.borderColor = UIColor.black.cgColor
        textField.layer.cornerRadius = 5
        textField.inputAccessoryView = UIView() // hides Done button from keyboard
        textField.withPrefix = true
        textField.withExamplePlaceholder = true
        textField.withFlag = true
        textField.withDefaultPickerUI = true
        textField.addTarget(self, action: #selector(checkPhoneNumberValidity), for: .editingChanged)
        return textField
}()

var phoneNumberKit: PhoneNumberKit!

override func viewDidLoad() {
        super.viewDidLoad()

        phoneNumberKit = PhoneNumberKit()
}

deinit {
        phoneNumberKit = nil
}

@objc func checkPhoneNumberValidity() {
        
        guard let phoneNumberText = phoneNumberTextField.text else { return }
        
        guard let phoneNumberKit = phoneNumberKit else { return }
        
        do {
            
            let phoneNumber = try phoneNumberKit.parse(phoneNumberText)
            
            let numberString = phoneNumber.numberString
            let countryCode = phoneNumber.countryCode
            let nationalNumber = phoneNumber.nationalNumber
            let numberExtension = phoneNumber.numberExtension
            let type = phoneNumber.type
            
            print("\nnumberString: \(numberString) | countryCode: \(countryCode) | nationalNumber: \(nationalNumber) | numberExtension: \(numberExtension as Any) | type: \(type)")
            
            let formattedPhoneNumberStr = phoneNumberKit.format(phoneNumber, toType: .e164)
            print("formattedPhoneNumberStr: \(formattedPhoneNumberStr)\n")
            
            if let regionCode = phoneNumberKit.mainCountry(forCode: phoneNumber.countryCode) {
                
                let country = Locale.current.localizedString(forRegionCode: regionCode)
                
                print("\nregionCode: \(regionCode) | country: \(country as Any)\n")
                
                let countryCodePlusNationalNumber = String(countryCode) + String(nationalNumber)
                print("countryCodePlusNationalNumber: \(countryCodePlusNationalNumber)\n")
                
                let isNumberValid = phoneNumberKit.isValidPhoneNumber(countryCodePlusNationalNumber, withRegion: regionCode, ignoreType: true)
                if isNumberValid {
                    
                    print("valid phone number")
                    
                } else {
                    
                    print("invalid phone number")
                }
            } else {
                print("regionCode is nil")
            }
        } catch {
            print("Generic parser error: ", error.localizedDescription)
        }
}
```
