### ISSUE TITLE
Unable to align phone code in iOS 13

### ISSUE THREAD

**Issue by roopesh63** [chronotruck/FlagPhoneNumber#124]
In iOS 13 phone code and flag button both misaligned but flag button alignment is fixed using edge insets property and can't able to do same with phone code like in attached image
![IMG_5068C02BEE70-1](https://user-images.githubusercontent.com/42858571/65571417-481b4500-df82-11e9-9aab-bdf218da3423.jpeg)

**Comment by MVakas** [comment]
Facing the same issue.

**Comment by MVakas** [comment]
<img width="237" alt="Screenshot 2019-09-25 at 11 13 25 AM" src="https://user-images.githubusercontent.com/7447077/65573972-9251f580-df85-11e9-98cd-b6e2e268d568.png">
<img width="238" alt="Screenshot 2019-09-25 at 11 13 36 AM" src="https://user-images.githubusercontent.com/7447077/65573975-9aaa3080-df85-11e9-8e25-78b281dbe650.png">

**Comment by grifas** [comment]
Can you try with the `fix_layout` branch ?

**Comment by MVakas** [comment]
Okay lemme try.

**Comment by MVakas** [comment]
Works. Thanks.

**Comment by Salmancs43** [comment]
Any solution?

**Comment by MVakas** [comment]
> Any solution?

try `fix_layout` branch

**Comment by grifas** [comment]
I pushed the fix on `0.7.7`
