### ISSUE TITLE
Search Bar doesn't appear on IOS less than 13

### ISSUE THREAD

**Issue by Black-riddle** [chronotruck/FlagPhoneNumber#147]
Hello, When I display countries using the FPNCountryListViewController the search bar appears only on its first display. When I dismiss FPNCountryListViewController and display it again it appears without the search bar. This problem only appears whith ios Less than 13.

**Comment by 2078prince** [comment]
Have you find any solution?

**Comment by Black-riddle** [comment]
Yes, in "FPNCountryListViewController"  I have changed one line. I used used the navigationItem.searchController with Ios 13 and above
`if #available(iOS 13.0, *) {
	navigationItem.searchController = searchController
 } else {
         searchController.dimsBackgroundDuringPresentation = false
          tableView.tableHeaderView = searchController.searchBar
	}`
PS: This worked for me ;)

**Comment by Black-riddle** [comment]
> Have you find any solution?

Yes, in "FPNCountryListViewController" I have changed one line. I used used the navigationItem.searchController with Ios 13 and above
if #available(iOS 13.0, *) { navigationItem.searchController = searchController } else { searchController.dimsBackgroundDuringPresentation = false tableView.tableHeaderView = searchController.searchBar }
PS: This worked for me ;)
