### ISSUE TITLE
Took too long to load

### ISSUE THREAD

**Issue by rehmanateeq** [chronotruck/FlagPhoneNumber#169]
I am using this library in my project. It is working properly on new devices but on older devices(iPhone 7 Plus) it took much longer time to load. I tried it with both storyBoard and programmatically. Please fix this ASAP

**Comment by athmane2197** [comment]
It's the same for me, it's take 6 seconds to load and for the User Experience it's really bad.
I think they are loading a HTTP Request (Post or Get) every times.
