### ISSUE TITLE
Ability to restrict set of phone numbers & flags

### ISSUE THREAD

**Issue by akilanarasu1994** [chronotruck/FlagPhoneNumber#20]
Hi @grifas .
It would be really great if the library allows the developer to restrict the flags & formats shown in the CTKFlagPhoneNumberTextField.
Some apps are only released in certain countries, hence it makes sense to restrict the phone numbers allowed to be entered into the text field.

**Comment by grifas** [comment]
Hi @akilanarasu1994 Yeah it's a really good idea. I add it as a new feature in the README ;)

**Comment by grifas** [comment]
@akilanarasu1994 What do you mean by `formats` ?

**Comment by akilanarasu1994** [comment]
@grifas Ahh yes, I forgot to mention that. Each country's phone number has a format. Restricting the flags that can be selected will correspondingly restrict the respective formats.

It would also be great if we could get the lengths of phone numbers for each country. That way, consumers can also use the length to validate the phone number.

**Comment by grifas** [comment]
@akilanarasu1994 It's possible now with `0.7.0` version :)
