### ISSUE TITLE
Disable Phone Number Format.

### ISSUE THREAD

**Issue by sonusurender** [chronotruck/FlagPhoneNumber#25]
Hi There,

First of all thank you for your great library. :)

I am implementing Country code picker into one of my app but i have one concern that i dont want to implement phone number formatting. But in your code formatting is by default. So is there any way to disable it?

Thank You!!

**Comment by grifas** [comment]
hi @sonusurender Thanks to use this lib ;)

Currently, there is no way to disable it, but I can add one in the next version or you can make a pull request for it. (It will be great because I have few time to work on it).

**Comment by aniketfluentcodeio** [comment]
Hi,

setWithPhoneNumber is not working trying to set contact number 

Thank's in advance

**Comment by grifas** [comment]
@aniketfluentcodeio please create a new issue.
