### ISSUE TITLE
Retrieve 2-letter country code

### ISSUE THREAD

**Issue by nickenchev** [chronotruck/FlagPhoneNumber#33]
I'm not sure if I'm overlooking something, but I can't seem to find a way to retrieve the country code. I tried extending the CTKFlagPhoneNumberTextField class and overriding the country picker delegate but I can't, since its not marked "open".

Please advise, thank you.

**Comment by grifas** [comment]
For now it's impossible but I can make it possible in the next release.

**Comment by nickenchev** [comment]
Thanks, any idea when thats happening? Otherwise I may just fork.

**Comment by grifas** [comment]
I don't want to make you a promise but may be at the end of this afternoon it will be release :)

**Comment by grifas** [comment]
I'm testing some improvements on `improvement` branch so you can try it and tell me if that resolves your issue.

Try to add CTKFlagPhoneNumberDelegate :)

**Comment by nickenchev** [comment]
Should I be adding the source directly to my project, or is there a pod I can install?

**Comment by grifas** [comment]
You have to specify the `improvement` branch in your Podfile, then `pod install`.

**Comment by nickenchev** [comment]
I think the delegate will do the trick, but you removed getPhoneNumber in place for the delegate method. This is cool, but I need to be able to check if whats currently in the text field is a valid phone #. With the new approach the delegate will fire, I'll store the phone number and get it ready to send to WS, same with country code. Problem is if the user changes the textfield between then and submitting, I wouldn't know if the text field contains an invalid value.

Any ideas?

**Comment by grifas** [comment]
Ok I see. I added in the delegate the `didValidatePhoneNumber(textField: CTKFlagPhoneNumberTextField, isValid: Bool)` function. It is triggered each time the user makes change. 

Can you try it ?

**Comment by nickenchev** [comment]
Perfect, thank you!

**Comment by nickenchev** [comment]
Hey, since the String is gone from the callback, as well as the `getPhoneNumber()` method, should users now be using `getFormattedPhoneNumber(format:)` to get the number as in previous versions?

**Comment by grifas** [comment]
yeah I think it's the right way to provide the phone number. Like that user chooses which format he wants to use.

**Comment by nickenchev** [comment]
I agree, only problem is from a library design perspective its kinda weird. In order for a user of your API to resolve the `NBEPhoneNumberFormat` type in Swift, they have to add `#import "NBPhoneNumberDefines.h"` in their Obj-C bridging header. This struck me as odd, maybe you should consider creating a Swift specific enum and map it to the NBE one. Its obviously not a big deal, just somewhat strange for a Swift.

**Comment by grifas** [comment]
Yeah thanks to see that. Now, I have to fix some issue with this improved code and I will release once it will be stable.

**Comment by grifas** [comment]
A new pod version, [0.6.0](https://github.com/chronotruck/FlagPhoneNumber/tree/0.6.0), is available. It should resolve your issue.
