### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by mohdimran3pg** [chronotruck/FlagPhoneNumber#36]
### Expected behavior
  Just like Android **setPhoneNumberValidityChangeListener**, there should be a callback or delegate method
### Actual behavior
  There is no way to validate entered phone number
### Steps to reproduce the problem.
  Simple to enter any phone number but you will not notify on your ViewController
### Specifications
  I am using one which you suggested into Github

**Comment by grifas** [comment]
You can add a target on your UITexField and use .editingChanged as UIControlEvents:

textfield.addTarget(self, action: #selector(updateTextField), for: .editingChanged)

Like that changes will trigger updateTextField function.

**Comment by mohdimran3pg** [comment]
Thanks for prompt response. 

The challenge part is how i will know that entered phone number is valid or not, Did you get my concern? As we know that different countries supports different number of digits. 

You are suggesting me to add a function on edit event of UITextField but that will not solve my issue.

**Comment by grifas** [comment]
For now, you can solve it with this workaround. And in the function target check `phoneNumberTextField.getFormattedPhoneNumber()`. If it returns the number so it's valid otherwise it returns nil.

**Comment by grifas** [comment]
Hi @mohdimran3pg I'm testing some improvements on `improvement` branch so you can try it and tell me if that resolves your issue.

Try to add CTKFlagPhoneNumberDelegate :)

**Comment by grifas** [comment]
A new pod version, [0.6.0](https://github.com/chronotruck/FlagPhoneNumber/tree/0.6.0), is available. It should resolve your issue.
