### ISSUE TITLE
facing issue when use it in scroll view

### ISSUE THREAD

**Issue by forTJ555** [chronotruck/FlagPhoneNumber#37]
when i have add CTKFlagPhoneNumber text field in scroll scroll then i am unable to edit it. its always show me country picker and m unable to enter phone number .  but when i add it outside main view then it works perfect

**Comment by forTJ555** [comment]
is there any response for issue?

**Comment by grifas** [comment]
Please next time use the template issue for creating one. 

So If I understand what you mean, `CTKFlagPhoneNumber` doesn't work in a `scrollView`. I will check that ;) but for now I'm sorry there is no workaround.

**Comment by forTJ555** [comment]
![simulator screen shot - iphone 6s - 2018-08-24 at 15 44 03](https://user-images.githubusercontent.com/42463540/44579615-932dbc00-a7b4-11e8-877c-88f59a9d54d8.png)

some time it doesn't display flag images.

**Comment by piroznoe** [comment]
func textFieldDidBeginEditing(_ textField: UITextField) {
///phoneRegistrationTextField.tag == 10
        if textField.tag == 10 {
            textField.keyboardType = .numberPad
            textField.tintColor = .blue
        }
    }

**Comment by qaavi** [comment]
Hi @forTJ555  Did you find the cause of this flags issue ?

**Comment by qaavi** [comment]
@grifas No I think this flag disappearance issue is something else

**Comment by grifas** [comment]
Which version of FlagPhoneNumber have you ?

**Comment by grifas** [comment]
Maybe what I said in #54 would help you ?

**Comment by qaavi** [comment]
HI @grifas , 

My issue is exactly the same (100%) as described in https://github.com/chronotruck/FlagPhoneNumber/issues/15  (No crash, but no flags are loaded when already logged in)

I've reported this issue at https://github.com/chronotruck/FlagPhoneNumber/issues/57

**Comment by grifas** [comment]
Try to do what @maniarali said in https://github.com/chronotruck/FlagPhoneNumber/issues/15#issuecomment-389805028. Did it fix the issue ?

**Comment by qaavi** [comment]
@grifas  No that also didn't help

**Comment by grifas** [comment]
@qaavi Maybe in your project you manipulate bundles when you log out of the app and that override the flag icons bundle ?

**Comment by qaavi** [comment]
Not at all. I’m not doing anything with flags/bundle load/unload. On login
page, where I’m using this lib, when I open it directly it works. But in
case where user is already logged in, I bypass login page and go directly
to home page. In this case, the flags bundle is mysteriously not loaded.

**Comment by grifas** [comment]
@qaavi See #54 maybe it can help you. Otherwise, maybe there is a conflict with the textField's constraints. You can see conflicts in the Debug View Hierarchy.

**Comment by grifas** [comment]
@forTJ555  @piroznoe @qaavi Any news ?

**Comment by qaavi** [comment]
@grifas Neither fixed, nor making any sense. Had to customise it from start. Any good news from you?

**Comment by grifas** [comment]
I really think it's about a conflicts with constraints. Did you investigate with `Debug View Hierarchy` ? 

Maybe the height of the textfield is too small for the size of the flag. Try to set the height of the textfield equals to 44 (constraint) and `textfield.flagSize = CGSize(width: 32, height: 32)`

**Comment by piroznoe** [comment]
no, sry

пн, 24 дек. 2018 г. в 14:40, Abdul Qavi <notifications@github.com>:

**Comment by qaavi** [comment]
@grifas I'm sure it's something related to Constraints. Ours issue is same as reported here -
[https://user-images.githubusercontent.com/29880773/40111843-b6ef703e-5921-11e8-97e8-e77b0a1716d2.png](url)
and
[https://user-images.githubusercontent.com/29880773/40164413-12ab92bc-59d7-11e8-9a10-7b19aef740cb.png](url)

**Comment by grifas** [comment]
@qaavi your links don't work

**Comment by qaavi** [comment]
https://github.com/chronotruck/FlagPhoneNumber/issues/15#issuecomment-389781034
and 
https://github.com/chronotruck/FlagPhoneNumber/issues/15#issuecomment-389471533

**Comment by grifas** [comment]
I improve the provide examples to help you.
