### ISSUE TITLE
Swift 4.2 and Xcode 10 support

### ISSUE THREAD

**Issue by gelemias** [chronotruck/FlagPhoneNumber#41]
### Expected behavior
Library compiling and working with Swift 4.2 and Xcode 10
### Actual behavior
It doesn't compile with 4.2

**Comment by grifas** [comment]
I will release the support as soon as possible today.

**Comment by grifas** [comment]
@gelemias Can you show me the error ? I'm using it in a projet with swift 4.2 and Xcode 10 and I have no error :/

**Comment by grifas** [comment]
Can you test with the [swift-4.2](https://github.com/chronotruck/FlagPhoneNumber/tree/swift-4.2) branch ?

**Comment by gelemias** [comment]
Its fine, thanks you. No errors but the format changes like for UIApplicationLaunchOptionsKey
