### ISSUE TITLE
Locale.current.regionCode could be nil

### ISSUE THREAD

**Issue by MattKiazyk** [chronotruck/FlagPhoneNumber#45]
We've gotten a few crashes in related to the following line: 

https://github.com/chronotruck/FlagPhoneNumber/blob/0a9688bd69c2d1ad572345aa381a506bdffc7bd5/FlagPhoneNumber/FlagPhoneNumberTextField.swift#L167

`Locale.current.regionCode` is an optional return - so it may return nil, which will crash as the code is adding a `!`

I'm not sure if the country picker supports having an empty country or not.

**Comment by grifas** [comment]
Hi thanks to report it. It's fixed on `0.7.1`.
