### ISSUE TITLE
After Selection Flag cursor becomes invisible and keyboard type changes automatically

### ISSUE THREAD

**Issue by Kalam95** [chronotruck/FlagPhoneNumber#47]
i have added a textfield(FPNTextField) in a stack view through interface builder 
then when i try to select from the ui my specific country it makes cursor invisible and keyboard becomes default for number-pad

**Comment by grifas** [comment]
Hi everyone, I will investigate this afternoon. I keep you in touch.

**Comment by grifas** [comment]
@Kalam95 Please fill out the issue template to describe yours. Closed as long as it's not filled out.
