### ISSUE TITLE
i would like to use india number 10 digits, without spaceing

### ISSUE THREAD

**Issue by santhoshappdev** [chronotruck/FlagPhoneNumber#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**
 - Version [e.g. 0.6.0]

**Additional context**

**Comment by grifas** [comment]
Please fill out the template issue to describe yours. Closed as long as it's not filled out.

**Comment by El-Diablo1** [comment]
if we are using textfield extension then the properties are not work properly
