### ISSUE TITLE
Keyboard type changes after country selection when used in tableview

### ISSUE THREAD

**Issue by UtkuDalmaz** [chronotruck/FlagPhoneNumber#51]
**Describe the bug**
Number keyboard pad lost after country selection when used in tableview (static)

**To Reproduce**
use it in a tableview (static) 
change country
keyboard type is not the number pad

**Expected behavior**
Keyboard type should stay in the number pad

**Smartphone (please complete the following information):**
 - Device: iphone x
 - OS: ios 12
 
 **FlagPhoneNumber (please complete the following information):**
 - Version: 0.7.1

**Comment by grifas** [comment]
@UtkuDalmaz Thanks to report it. Just to be sure, Is `Version latest` equal to `0.7.1` ?

**Comment by UtkuDalmaz** [comment]
yes

**Comment by UtkuDalmaz** [comment]
It is solved but setting delaysContentTouches to false breaks tableview scroll when touched to the screen. Not a proper fix.

**Comment by grifas** [comment]
I think it's the best solution when `UITextField` is included in a `UITableView`.
