### ISSUE TITLE
Remove Flag

### ISSUE THREAD

**Issue by maulik6994** [chronotruck/FlagPhoneNumber#59]
Do not want  to show flag how can I do that? 

I want to show only number with Country.

**Comment by grifas** [comment]
@maulik6994 Please fill out the feature request template to describe yours. Closed as long as it's not filled out.

**Comment by OudomSec** [comment]
Hello Mr! I want to remove the flag from my TextField, I only want the country code to show in my TextField, how can I remove the flag?
