### ISSUE TITLE
Bring up the country picker by tapping the country code.

### ISSUE THREAD

**Issue by jasonwong2065** [chronotruck/FlagPhoneNumber#60]
**Is your feature request related to a problem? Please describe.**
Hello! A nice improvement would be the ability to tap the country code to bring up the country code picker. Currently, only tapping the flag brings up the country picker.

**Describe the solution you'd like**
Tapping the country code e.g. "+00" will bring up the country picker to allow selecting another country.

**Describe alternatives you've considered**
I tried to make another invisible button centred on the country code to get it to trigger the country picker, but I couldn't get it working.

**Additional context**
I was trying to hide flags while still allowing the changing of the country codes but I couldn't quite create a fix. Thanks for making this library, it's really useful.

**Comment by barkiiqbal** [comment]
i am also looking into this kind of feature but did not find any. Any guide?

**Comment by jasonwong2065** [comment]
Hello! What I did was create a button with a clear background in front of the country code which sends an event to an action handler which simulates a touch on a 0 size flag. 

Not an elegant solution but gets the job done, hopefully someone else has a better solution because I can't think up of any :P

**Comment by barkiiqbal** [comment]
Thanks, did you edit the library for that or do it in your application.

**Comment by jasonwong2065** [comment]
I did it in my application, I think I did it by either setting the insets
of the flag or the size of the flag.

**Comment by danielebaschirotto** [comment]
It is a bit late but since the issue is still open I suggest a possible solution.
leftView is the left part including the country code so we can add a gestureRecognizer like this:

phoneNumberTextField.leftView?.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(didTapOnCountry)))

@objc func didTapOnCountry() {
        fpnDisplayCountryList()
    }

**Comment by jasonwong2065** [comment]
Thanks! I don't think I need a solution anymore. Have since stopped working on it, but hope that your solution helps others.
