### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by tianzhuqiao** [chronotruck/FlagPhoneNumber#61]
The project is cool, thanks!  Is there any plan to support Carthage? 

Thanks

**Comment by tianzhuqiao** [comment]
Thanks for the quick update. Tried 0.7.2 with Carthage, it compiles fine; but when run on device, it complains that it can't find libPhoneNumber-iOS.

**Comment by grifas** [comment]
@tianzhuqiao I fixed the issue. To be sure, could you try it ? The branch is `hotfix/carthage`.

**Comment by tianzhuqiao** [comment]
Try hotfix/carthage branch, it says:

> Dependency "FlagPhoneNumber" has no shared framework schemes for any of the platforms: iOS

Maybe we also need to include the following folder?

> .xcodeproj/xcshareddata/xcschemes

**Comment by grifas** [comment]
@tianzhuqiao It should be ok now. Don't forget to import `libPhoneNumberiOS.framework` with `FlagPhoneNumber.framework`.

**Comment by tianzhuqiao** [comment]
Thanks a lot, @grifas. It works now!

**Comment by grifas** [comment]
I made some updates about Carthage support in `0.7.3`.

**Comment by tianzhuqiao** [comment]
Thanks @grifas!
