### ISSUE TITLE
Getting invalid number for number which starting from 6005 series

### ISSUE THREAD

**Issue by Neelu1112** [chronotruck/FlagPhoneNumber#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**
 - Version [e.g. 0.6.0]

**Additional context**

**Comment by grifas** [comment]
Please fill out the issue template to describe yours. Closed as long as it's not filled out.
