### ISSUE TITLE
FPNTextFieldDelegate delegate methods not called

### ISSUE THREAD

**Issue by marcelfagadariu** [chronotruck/FlagPhoneNumber#66]
**Describe the bug**
My 2 delegate methods are not called after conforming to the protocol.
I respected all the steps done in your project but still delegate methods not triggered.

**To Reproduce**
Done by the book step by step as yours

**Screenshots**
![screenshot 2019-01-17 at 16 34 19](https://user-images.githubusercontent.com/16760233/51325562-e4955b00-1a75-11e9-84dc-2413bbedb9ab.png)
![screenshot 2019-01-17 at 16 34 25](https://user-images.githubusercontent.com/16760233/51325570-e95a0f00-1a75-11e9-9913-2caabd1df60e.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 6s
 - Version 12.1.2

**Comment by dylanreich** [comment]
You need to call `textFieldNumber.flagPhoneNumberDelegate = self` in line 22. That should do the trick.

**Comment by marcelfagadariu** [comment]
Hey. Thanks for the reply @dylanreich . I've managed to make it work as you said. 

Any idea why 

`textField.getFormattedPhoneNumber(format: .E164),
  textField.getFormattedPhoneNumber(format: .International),
 textField.getFormattedPhoneNumber(format: .National),
 textField.getFormattedPhoneNumber(format: .RFC3966),
 textField.getRawPhoneNumber()`

are nil when I enter the predefined number which is shown on the keyboard? 
If I type it manually it/s working...but if I select that predefined number from my Numpad keyboard all FPNTextField are nil

**Comment by marcelfagadariu** [comment]
> Hey. Thanks for the reply @dylanreich . I've managed to make it work as you said.
> 
> Any idea why
> 
> `textField.getFormattedPhoneNumber(format: .E164), textField.getFormattedPhoneNumber(format: .International), textField.getFormattedPhoneNumber(format: .National), textField.getFormattedPhoneNumber(format: .RFC3966), textField.getRawPhoneNumber()`
> 
> are nil when I enter the predefined number which is shown on the keyboard?
> If I type it manually it/s working...but if I select that predefined number from my Numpad keyboard all FPNTextField are nil

Well ... I kinda solved my problem putting keyboard type on Decimal Pad and change the content type of keyboard to unspecified ... it was on telephone number previously

**Comment by ElliotCambo** [comment]
This still appears to be an issue, i am running 0.7.2 and the delegates seemingly do not get called. ive been trying to use this for 3 hours now and nothing is working. 

i have taken all advice from above , flagPhoneNumberDelegate is not a method apparenlty either.

**Comment by ElliotCambo** [comment]
I am not sure how the sample project is working but in my case the delegates are not called under any circumstance. I have started a new project and everything works correctly. However, in my main project I get a crash at the line phoneNumberTextField.parentViewController = self. Has anyone got any ideas as to how to resolve this problem. As always I get a SIGABRT Error throne which is useless When it comes to debugging.

**Comment by ElliotCambo** [comment]
God this is painful, any ideas, so when i get the SIGABRT, i actually get an error  > Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView rangeOfCharacterFromSet:]: unrecognized selector sent to instance 0x11d804e60' <  any ideas, this really shouldnt be this difficult

**Comment by ElliotCambo** [comment]
If i comment out the line >> phoneNumberTextField.parentViewController = self
i get this > Thread 1: EXC_BAD_ACCESS (code=257, address=0x6f436e69617465)

**Comment by marcelfagadariu** [comment]
Hey @ElliotCambo . Maybe it will help u.

@IBOutlet weak var textFieldNumber: FPNTextField!
Also in Identity Inspector set the class FPNTextField and the module to FlagPhoneNumber.

in viewDidLoad ->  set : textFieldNumber.flagPhoneNumberDelegate = self

**Comment by grifas** [comment]
@ElliotCambo  Do you resolve your issue ? Otherwise, can you use the last version and retry ?

**Comment by luai-kalkatawi** [comment]
@grifas the issue is continue

**Comment by grifas** [comment]
@luai-kalkatawi Can I see how you instance it ?

**Comment by kayodeAdachypay** [comment]
In case someone is having the same issue, I had the same issue and I solved it by asserting the delegate after adjusting the phoneTextField and inserting it into the UI.
