### ISSUE TITLE
Obj-C based project compatibility

### ISSUE THREAD

**Issue by jvanakker** [chronotruck/FlagPhoneNumber#68]
**Is your feature request related to a problem? Please describe.**
FlagPhoneNumber as it is, is not compatible for use in Objective-C projects. It Xcode creates a bridging header but most features (methods and delegates) won't work as it was originally.

**Describe the solution you'd like**
FlagPhoneNumber to be fully compatible within Obj-C based projects. I have provided a pull-request that adds basic Objective c project compatibility. **I did however import the Swift sources for FlagPhoneNumber (AND of course libPhoneNumberiOS.framework) manually in my project to get it working. So not using Cocoapods here.**

**Describe alternatives you've considered**
Imported the FlagPhoneNumber sources manually into Objective-C project. It still didn't fully work, added changes to make it compatible.

**Comment by ramz3001** [comment]
can you please provide a detail instruction on how to integrate it to objective c projects ?

**Comment by grifas** [comment]
I fixed an issue and provided an example for Objective-C in the new release `0.7.5`
