### ISSUE TITLE
Right to Left languages issue

### ISSUE THREAD

**Issue by didanoff** [chronotruck/FlagPhoneNumber#69]
In Right to Left languages text field start for the left side but not from the flag:
![simulator screen shot - iphone 7 - 2019-01-20 at 20 28 52](https://user-images.githubusercontent.com/8376119/51443598-c3da3900-1cf3-11e9-93e9-441c91d1dd53.png)

**Comment by grifas** [comment]
@didanoff Please fill out the issue template to describe yours. Closed as long as it's not filled out.

**Comment by grifas** [comment]
It's now available on `0.7.5`.

**Comment by Rcicen** [comment]
Hello, Can you add RTL for the countryPicker as well. Currently the dialCodes and the Country names are located in wrong order horizontally.

![Screen Shot 2019-05-29 at 17 46 24](https://user-images.githubusercontent.com/44670959/58566786-e64c0800-8239-11e9-83e7-33233e0546b9.png)

Dial code should be next to the flags if I am correct, and country names should be at the leftmost :)
