### ISSUE TITLE
FlagPhoneNumber inside TableView

### ISSUE THREAD

**Issue by sadiqsiddiqui** [chronotruck/FlagPhoneNumber#71]
**Describe the bug**
I'm using FPN inside tableview. On scroll the first country gets selected.

**To Reproduce**
1. Go to 'Any screen that contains FPN inside table view'
2. Click on 'Select a country'
3. Scroll down to 'Scroll tableview'
4. FPN selects the default country 

**Expected behavior**
It should retain last selected country.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 7+
 - OS: 12.x
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**

**Additional context**

**Comment by grifas** [comment]
Do you use a static or a dynamic cell ? If it's a static it should be work, you can try on the provided example.

In the other case, I think you have to save the last selected country and set it to the textField when the cell appears on the screen.
