### ISSUE TITLE
Add carthage error

### ISSUE THREAD

**Issue by ikbalyasar** [chronotruck/FlagPhoneNumber#72]
Carthage dont download dependency framework. 
I getting error.
"dyld: Library not loaded: @rpath/libPhoneNumber_iOS.framework/libPhoneNumber_iOS"

Carthage file add only this;
github "chronotruck/FlagPhoneNumber"

while download libPhoneNumber_iOS framework?

**Comment by grifas** [comment]
`FlagPhoneNumber` has a dependency named `libPhoneNumber_iOS` so you also have to import it.

Keep me in touch.

**Comment by ikbalyasar** [comment]
Doesn't have to come automatically `libPhoneNumber_iOS`  framework? Why  am I need import ?

**Comment by grifas** [comment]
Actually you have to add it like `Embedded Binaries` but I will think about another way. Sorry I'm not at ease with Carthage.

**Comment by ikbalyasar** [comment]
Please can you fixed this error.
And carthage need `libPhoneNumber_iOS` but carthage download `libPhoneNumberiOS`
I am getting this error;
`dyld: Library not loaded: @rpath/libPhoneNumber_iOS.framework/libPhoneNumber_iOS`

**Comment by shinrikiken** [comment]
I have the same error

**Comment by ikbalyasar** [comment]
@shinrikiken I passed the problem by adding a manual.

**Comment by OleksandrKatrynets** [comment]
I downloaded both Carthage's: 
- libPhoneNumber_iOS
- FlagPhoneNumber

**Comment by ikbalyasar** [comment]
Carthage does'nt work. You try manuel. İts work for me

**Comment by grifas** [comment]
Carthage Support is now available in `0.7.3`.
