### ISSUE TITLE
Flags don't appear

### ISSUE THREAD

**Issue by KarinaFernandez** [chronotruck/FlagPhoneNumber#73]
**Describe the bug**
The flags don't appear. Also I tried changing the Bundle path, but it always return `self.flag = UIImage(named: "unknown", in: Bundle.FlagIcons, compatibleWith: nil)`

**To Reproduce**
1. Load the VC whose has the txf 
2. Run the app

**Expected behavior**
Appear the flag in the scrolldown

**Screenshots**
The flags don't appear.
![simulator screen shot - iphone xs - 2019-02-21 at 16 10 27](https://user-images.githubusercontent.com/11321277/53195077-a26eb480-35f3-11e9-9f57-b67c13b081c2.png)

**Smartphone (please complete the following information):**
iPhone X, iPhone 5s
 
 **FlagPhoneNumber (please complete the following information):**
 - Version from brunch: 4.2
-  Version from brunch: Master

**Additional context**
I tried all the steps of the other related issues: [#15](https://github.com/chronotruck/FlagPhoneNumber/issues/15#issuecomment-389755897) and [#57](https://github.com/chronotruck/FlagPhoneNumber/issues/57).

Thank you so much in advance!

**Comment by grifas** [comment]
Very weird issue and like others, I don't know how to fix this one because I can't reproduce it. Could you share with me your project and I will investigate on it ?

**Comment by grifas** [comment]
Or may be you override the `Bundle.FlagIcons` ?

**Comment by kevinrenskers** [comment]
Exact same issue here :(

**Comment by KarinaFernandez** [comment]
Of course! Allow me a few days to create a basic project to integrate it and share it with you. Thank you very much for the quick response.

**Comment by dbeleza** [comment]
I have exactly the same issue here. For some unknown reason, on `FPNCountry.swift`, line 14, the `code` parameter is being sent but is still returning `nil`.

**Comment by grifas** [comment]
@KarinaFernandez what about of the basic project with the issue ? :)

**Comment by HoussamAlrifai** [comment]
I have exactly the same issue ,but in my situation  the problem disappear when  view controller containing flag phone number  is placed  in   main.storyboard

**Comment by juandavidcardona** [comment]
It's the same, sometimes the flags appear, others do not  :(

**Comment by Kriptite** [comment]
Copying FlagKit.xcassets to the app itself and adding this line to the AppDelegate didFinishLaunchingWithOptions fixed it for me
`Bundle.FlagIcons = Bundle(for: type(of: self))`

**Comment by KarinaFernandez** [comment]
Hi @grifas!  Sorry for the delay!
I have finally created a [repo](https://github.com/KarinaFernandez/FlagPhoneNumber) and it works with the version 0.7.2 but without success in older versions.

Thank you so much for the support!

**Comment by grifas** [comment]
A workaround is like @Kriptite said:



> Copying FlagKit.xcassets to the app itself and adding this line to the AppDelegate didFinishLaunchingWithOptions fixed it for me
> `Bundle.FlagIcons = Bundle(for: type(of: self))`

**Comment by hyd00** [comment]
> Copying FlagKit.xcassets to the app itself and adding this line to the AppDelegate didFinishLaunchingWithOptions fixed it for me
> `Bundle.FlagIcons = Bundle(for: type(of: self))`

How to write this line in Objective-C ? Please reply as I am on the verge of submitting my app to app store but Flags not appearing :(

**Comment by hyd00** [comment]
> A workaround is like @Kriptite said:
> 
> > Copying FlagKit.xcassets to the app itself and adding this line to the AppDelegate didFinishLaunchingWithOptions fixed it for me
> > `Bundle.FlagIcons = Bundle(for: type(of: self))`

Please help me with a work around for resolving this flag issue in Objective-C project.

**Comment by grifas** [comment]
@hyd00 here the line in Objective-C:

`NSBundle.FlagIcons = [NSBundle bundleForClass: [self class]];`

**Comment by hyd00** [comment]
@grifas Property 'FlagIcons' not found on object of type 'NSBundle'

This error pops up.

**Comment by grifas** [comment]
Maybe you need to clear your project and rebuild:

- Command + Shift + K.
- Command + Shift + Option + K
- Delete derived data

**Comment by hyd00** [comment]
@grifas Thanks!

**Comment by hyd00** [comment]
@dbeleza  and everyone else. What worked for me is :

1. Copying all the images in `FlagKit.xcassets` in my projects `Assets` and deleting all 1x and 3x files of all Flags. Just keep 2x Files.

2. Changing the line 14 - 18 in `FPNCountry.swift` from 
```
if let flag = UIImage(named: code, in: Bundle.FlagIcons, compatibleWith: nil) {
	self.flag = flag
} else {
	self.flag = UIImage(named: "unknown", in: Bundle.FlagIcons, compatibleWith: nil)
}
```

to 

```
if let flag = UIImage(named: code) {
	self.flag = flag
} else {
	self.flag = UIImage(named: "unknown")
}

```

**Comment by AhmedMohamedAllam** [comment]
I fixed it by replacing flag assets by get country flag from system with country code
`func getFlag(country:String) -> String {
        let base : UInt32 = 127397
        var s = ""
        for v in country.unicodeScalars {
            s.unicodeScalars.append(UnicodeScalar(base + v.value)!)
        }
        return String(s)
    }`
and the flag now is from type String so I changed the UIImageView to be UILabel and bind .text property to the new flag string.
you can check the changes in this fork
https://github.com/AhmedMohamedAllam/FlagPhoneNumber

**Comment by rajaonah-toky** [comment]
> Very weird issue :/ Some people have it and I don't know how to fix it because I can't reproduce it. Could you share me your project and I will investigate on it ?

I've exactly the same issue, 
we I run the project on Xcode, the flag appear,  but when I upload the app on testFlight, the flag doesn't appear anymore

**Comment by hyd00** [comment]
@madhur2603 and @rajaonah-toky the solution is written by ahmed and myself in the thread, do that and you will get flags in release build too.
