### ISSUE TITLE
Unable to change textcolor+tintcolor of searchbar/searchController of country search screen

### ISSUE THREAD

**Issue by Mehul18292** [chronotruck/FlagPhoneNumber#75]
**Describe the bug**
Unable to change textcolor+tintcolor of searchbar/searchController of country search screen. As I am having my screen theme with different color, if i am using your library, then the textcolor as well as tintcolor of searchbar/searchcontroller in search screen is not as per my app's theme. And you kept that viewcontroller as private, so i cant access the same. So, either keep that viewcontroller as public, so that we can accesss the same and make changes in UI OR add some way to update the same.

**Comment by gonzaaasanchez** [comment]
I'm having the same problem. We would really appreciate that improvement

**Comment by grifas** [comment]
This issue should be resolved in the new version. (0.8.0)
