### ISSUE TITLE
swift 4.1 not supported

### ISSUE THREAD

**Issue by kukkadapukarthik** [chronotruck/FlagPhoneNumber#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**
 - Version [e.g. 0.6.0]

**Additional context**

**Comment by kukkadapukarthik** [comment]
Module compiled with Swift 4.1 cannot be imported in Swift 3.2.3:

**Comment by kukkadapukarthik** [comment]
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

**Comment by grifas** [comment]
`Swift Language Version` is set to `Swift 5`
