### ISSUE TITLE
How to change textField placeholder number? It's incorrect.

### ISSUE THREAD

**Issue by PavelSakhanko** [chronotruck/FlagPhoneNumber#83]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**
 - Version [e.g. 0.6.0]

**Additional context**

**Comment by swift4developer** [comment]
Add a new override property 
`open override var placeholder: String? {
        didSet {
            phoneCodeTextField.text = placeholder
        }
    }`

`textField.placeholder = "Some Placeholder"`
