### ISSUE TITLE
ToolBar with done button for textfield is being removed after country selection.

### ISSUE THREAD

**Issue by olivierc-medopad** [chronotruck/FlagPhoneNumber#84]
**Describe the bug**
Doesn't seem like there's a done UIBarButton on a ToolBar for the numpad when typing the phone number (although there is one for the country selection). I manually added a tool bar with a done button for the textfield. Works as long as you don't choose your country. If done so, the toolbar disappears (is the toolbar thing getting reset on dismissing the country picker?)

**To Reproduce**
1. Open the FPNTextField
2. Click on the flag to select a country
3. Click on the textfield again
4. Toolbar is not there anymore

**Expected behavior**
I would have expected my toolbar to stay on the numpad for the phone number textfield even after choosing a country

**Smartphone (please complete the following information):**
 - All devices
 
 **FlagPhoneNumber (please complete the following information):**
 - Latest version

Any help welcome, I didn't take time to dig in the code yet, just if ever I was configuring something in a wrong way. If not, I might go have a look at it.

Regards

**Comment by grifas** [comment]
You have to set your toolbar to the `textFieldInputAccessoryView` property of the FPNTextField. It should resolve your issue.

```
phoneNumberTextField.textFieldInputAccessoryView = yourToolBar
```
