### ISSUE TITLE
extension problem

### ISSUE THREAD

**Issue by El-Diablo1** [chronotruck/FlagPhoneNumber#85]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 0.6.0]
 
 **FlagPhoneNumber (please complete the following information):**
 - Version [e.g. 0.6.0]

**Additional context**
![Screen Shot 2019-05-23 at 11 26 40 AM](https://user-images.githubusercontent.com/41420757/58230436-c30eed80-7d4d-11e9-92df-beda874ded53.png)
i got this issue when i try to customize the properties

**Comment by grifas** [comment]
I can't help you if I have no more information so please fill the issue template.
