### ISSUE TITLE
logo Proposal

### ISSUE THREAD

**Issue by davidmind** [chronotruck/FlagPhoneNumber#86]
Hi @akilanarasu1994, I am a graphics designer. I will like to know of you want me to create a new logo for this project.

**Comment by grifas** [comment]
Hi @davidmind, I'm the owner of this little project. 

It would be cool to have a logo for it. Do you have suggestion ?

**Comment by davidmind** [comment]
@grifas yea. Here is what I came up with
![Flagnumber.png](https://cdn.steemitimages.com/DQmetY5i31vGF8rjGxdR4pxkC2xKpYV8yZfPfmydgRf1QBn/Flagnumber.png)

**Comment by grifas** [comment]
You used android guidelines (material) to made your suggestion. I think it's not good for a iOS library to have a logo like this...

**Comment by davidmind** [comment]
Ok, what will like to know is if you like the logo concept?
So that I can adjust the logo to meet up with iOS standard.

**Comment by davidmind** [comment]
@grifas below is an IOS preview version of the logo
![IOS-Flagnumber.png](https://cdn.steemitimages.com/DQmUW5BjZeKGNQrdE5Fue842X5JBw3mXeocVwmTc84FqRot/IOS-Flagnumber.png)

**Comment by grifas** [comment]
@davidmind Thanks for your work but I will not follow up it.

**Comment by davidmind** [comment]
OK, thanks for your time. But can you give me reason for rejection. May be I can improve the logo to something better

**Comment by grifas** [comment]
The reason is I asked to someone else in internal :)

**Comment by davidmind** [comment]
OK, all the best.
