### ISSUE TITLE
Unable to change placeholder textcolor

### ISSUE THREAD

**Issue by Rcicen** [chronotruck/FlagPhoneNumber#87]
**Is your feature request related to a problem? Please describe.**

Due to the apps design the textField has a dark background and therefore I need to change the placeholders color to make it visible.
The app i'm working on is written in Objective C and i think due to the lack of compatibility with Obj-C, I am unable to change the placeholder color. I have tried to assign an attributed string to the placeholder but since it is an String? Xcode won't allow it.

**Describe the solution you'd like**
Easy method to change the placeholder color would be great

**Additional context**

**Comment by swift4developer** [comment]
Add the below code in FlagPhoneNumberTextField.swift file.

` open override var placeholder: String? {
        didSet {
            phoneCodeTextField.text = placeholder
        }
    }
    
    open override var attributedPlaceholder: NSAttributedString? {
        didSet {
            phoneCodeTextField.attributedPlaceholder = NSAttributedString(string: placeholder ?? "512356987", attributes: [NSAttributedString.Key.foregroundColor: UIColor.white])
        }
    }`
