### ISSUE TITLE
ITMS-90035 error caused by GeneratePhoneNumberHeader.sh

### ISSUE THREAD

**Issue by tianzhuqiao** [chronotruck/FlagPhoneNumber#95]
For the latest version (0.7.5), **GeneratePhoneNumberHeader.sh** is included in the target, which fails when uploading to app store (Error itms-90035). Looks like we add the script to target since 0.7.4. 

Do we need this file for the target? And could we remove it? Thanks.

**Comment by grifas** [comment]
I removed it from the target. A new release is available (`0.7.6`).
