### ISSUE TITLE
SetFlag Not working after update last version

### ISSUE THREAD

**Issue by SelvaMacApp** [chronotruck/FlagPhoneNumber#96]
<img width="476" alt="Screenshot 2019-06-04 at 12 58 10 PM" src="https://user-images.githubusercontent.com/37236348/58859993-b92fa780-86c8-11e9-898e-d60bc68a50da.png">

**Comment by SelvaMacApp** [comment]
SetFlag Not working after update last version

**Comment by grifas** [comment]
@SelvaMacApp Please fill out the issue template because I have no more information about your issue.

**Comment by khoren93** [comment]
@SelvaMacApp try this))
`self.mobileNumber.setFlag(for: FPNOBJCCountryKey.US)`

**Comment by romain64** [comment]
**Error: Ambiguous use of 'setFlag(for:)'**

There is a conflict between the two public methods
`public func setFlag(for countryCode: FPNCountryCode)`
and `@objc public func setFlag(for key: FPNOBJCCountryKey)`

**Comment by zishanj** [comment]
It does shows *Ambiguous use of 'setFlag(for:)'*. But if I use with `FPNCountryCode.AE` like this `.setFlag(for: FPNCountryCode.US` then it works.
