### ISSUE TITLE
Objective C pod install error

### ISSUE THREAD

**Issue by ArvndS** [chronotruck/FlagPhoneNumber#98]
pod 'FlagPhoneNumber', :path => '../'

**Comment by ArvndS** [comment]
pod 'FlagPhoneNumber', :path => '../' using the path i'm not able install this pod in objective c, and if install normal  pod 'FlagPhoneNumber' like this means I'm not able to import the file in objective c

**Comment by grifas** [comment]
What is the error ?

**Comment by ArvndS** [comment]
No podspec dependency file found For this path pod 'FlagPhoneNumber', :path => '../'

**Comment by grifas** [comment]
`pod 'FlagPhoneNumber', :path => '../'` is to use for my example project. In your project, you just have to use `pod 'FlagPhoneNumber'`.

**Comment by ArvndS** [comment]
Thanks for your reply bro..
