### ISSUE TITLE
Can't import countries from string

### ISSUE THREAD

**Issue by payamprivate** [chronotruck/FlagPhoneNumber#99]
**Additional context**

Hi Dear
I searched a lot before submitting this issue but I couldn't find any solution
In my application i get supported countries through an API , so I have to set countries with string country codes
but this FlagPhoneNumber has only one way to set countries and it uses an enum
its like this:
falg_phone_number.setCountries(including: [.FI, .SE])

I really need a method to set countries using a string like this:
flag_phone_number.setCountries("FI,SE")

please help me if there is a way
thanks

**Comment by grifas** [comment]
You can do it with the current version.

`FPNCountryCode` can be initialised with String so:
```
let array: [FPNCountryCode] = []

if let code = FPNCountryCode(rawValue: "FI") {
	array.append(code)
}

if let code = FPNCountryCode(rawValue: "SE") {
	array.append(code)
}

phoneNumberTextField.setCountries(including: array)
````

You just have to split your string ("FI,SE").

**Comment by payamprivate** [comment]
Thank you <3
